# Site settings 配置站点
title: Gchr
description: 
keyword: 'java, program, computer, tech, cs'
# url: 'http://ray-eldath.tech' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2017

# Author 配置博主信息
author: 'Chunru Gong'
nickname: 'inoeverything'
bio: '哈哈，加油!'
# avatar: 'https://res.cloudinary.com/ray-eldath/image/upload/basic/avatar.jpg'

# Search
search: true

# Night mode
nightMode: false

# Global comments setting
comments: true

# Comments
disqus: false
disqus_url: 'https://gongchunru.disqus.com/embed.js'

livere: false
livere_uid: 

# Reward 赞赏功能 by Ray-Eldath
reward:
  enable: true
  reward_comment: '真诚赞赏 手有余香'
  wechatpay: 'http://ww1.sinaimg.cn/large/65893557ly1fs1oxvjo7cj20ff0ffdhf.jpg'
  alipay: 'http://ww1.sinaimg.cn/large/65893557gy1fs1ou2rjjwj20d40d7js7.jpg'

# b2t 回到顶部 by Ray-Eldath
b2t: true

# MathJax 公式支持
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: 'mailto:gonchunru@gmail.com'
  # zhihu: '//www.zhihu.com/people/eldath-ray/activities'
  # github: '//github.com/Ray-Eldath'
  twitter: '//twitter.com/chunrugong'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]


# Google Analytics
google_analytics: UA-131584434-1